name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "deno install -gArf jsr:@deno/deployctl"

      - name: Build step
        run: "deployctl deploy --project=deepsider-2-api"
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}  # 添加这行

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "deepsider-2-api"
          entrypoint: "main.ts"
          root: ""
          token: ${{ secrets.DENO_DEPLOY_TOKEN }}  # 添加这行
